# Generated by Django 4.1 on 2022-08-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0001_initial"),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="maindish",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="maindish",
            field=models.ManyToManyField(to="foods.maindish"),
        ),
    ]
