# Generated by Django 4.1 on 2022-08-27 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0002_remove_cartitem_maindish_cartitem_maindish"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "desserts",
                    models.ManyToManyField(blank=True, null=True, to="foods.dessert"),
                ),
                ("maindish", models.ManyToManyField(to="foods.maindish")),
                ("sidedishes", models.ManyToManyField(to="foods.sidedish")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="desserts",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="maindish",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="sidedishes",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="user",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
